export const inputs = [
  {
    id: 1,
    name: "name",
    type: "text",
    placeholder: "Name",
    errorMessage:
      "Name should be 3-16 characters and shouldn't include any special characters",
    label: "Name",
    pattern: "^[A-Za-z0-9]{3,16}$",
    required: true,
  },
  {
    id: 2,
    name: "email",
    type: "email",
    placeholder: "Email",
    errorMessage: "Please enter a valid email address",
    label: "Email",
    required: true,
  },
  {
    id: 3,
    name: "date",
    type: "date",
    placeholder: "Date of Birth",
    label: "Date of Birth",
    required: true,
  },
  {
    id: 4,
    name: "password",
    type: "password",
    placeholder: "Password",
    errorMessage:
      "Password should be between 8-20 characters and include at least 1 letter, 1 number and 1 special character",
    label: "Password",
    pattern: `^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{8,20}$`,
    required: true,
  },
  {
    id: 5,
    name: "confirmPassword",
    type: "password",
    placeholder: "Confirm Password",
    errorMessage: "Passwords don't match",
    label: "Confirm Password",
    pattern: values.password,
    required: true,
  },
];
